### ISSUE TITLE
px-vis-register doesnt flow correctly in IE10

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis#1]
<img width="561" alt="screen shot 2016-06-13 at 11 42 01 am" src="https://cloud.githubusercontent.com/assets/1649404/16019186/85334e42-315c-11e6-898d-62d89830b6da.png">

In IE10, the top register does not flow correctly, as seen in px-vis-timeseries. Probably a flex bug. Title and values should be inline with the color bar and not overflowing onto the chart.

**Comment by runn-vermel** [comment]
Layout now works in all browsers
Safari 8+9
IE10+11+Edge
Chrome 50+51
Firefox 47
