### ISSUE TITLE
Should fix up Vis Framework page on predix-ui site.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis#103]
Vis Framework page on predix-ui https://www.predix-ui.com/#/elements/vis/px-vis/px-vis has couple of issues :
1. Hovering over px-vis-multi-axis component causes console log errors.

2. In px-vis-striping, stripes bleeding out of the chart overlaying the x-axis.

### Issue 1:
![screen shot 2017-08-29 at 3 18 05 pm](https://user-images.githubusercontent.com/10835611/29847621-78a61db8-8cd1-11e7-8b2b-0adece1389b8.png)

### Issue2:

![screen shot 2017-08-29 at 3 48 42 pm](https://user-images.githubusercontent.com/10835611/29847637-997bae22-8cd1-11e7-81e4-2644be79dbd4.png)

**Comment by Menkhaus-ge** [comment]
Issue 1 is fixed.

**Comment by Menkhaus-ge** [comment]
@nonmetalhail can you check out Issue 2
