### ISSUE TITLE
Resolve Codepen issues for vis components.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis#104]
On predix-ui site https://www.predix-ui.com/#/elements/vis/px-vis/px-vis, vis components' code pens throw 500 errors.
Opening this tracking issue to make a decision on whether we should disable codepens for vis component or decide if codepens are even needed for vis specific components.

![screen shot 2017-08-31 at 9 45 20 am](https://user-images.githubusercontent.com/10835611/29934791-525e763a-8e31-11e7-9fa9-558ff98a6e8b.png)

**Comment by randyaskin** [comment]
Hid all the codepens in v3.1.20 of vis since they don't really make sense in isolation / too much effort to manually maintain.
