### ISSUE TITLE
[toolbar] Allow to run several functions in actionConfig

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-vis#109]
right now when configuring an `actionConfig` you can only run one method for each event. 

We should extend that to allow an array of functions/string mapping so that several functions can be run

**Comment by nonmetalhail** [comment]
Why? Why can't you just do one method that calls several other methods?

**Comment by benoitjchevalier** [comment]
just to allow support of our "default mapping" that people don't necessarily have access to. They could then mix function and  mappings

**Comment by benoitjchevalier** [comment]
added in 4.6.0
