### ISSUE TITLE
Remove Comic Sans from px-vis-axis

### ISSUE THREAD

**Issue by davidnguyen1126** [PredixDev/px-vis#110]
Hi,

Yes I know if could change the font family with CSS but I think it would be better if you didn't default the axis to Comic Sans in the first place.  Could you please remove this so that I don't have to override it with CSS?  It would help keep our code base cleaner.  Thank you.

**Comment by nonmetalhail** [comment]
The charts and design system as a whole contain many placeholder defaults which are intended to be replaced with a theme. They should not be used without a theme and this is no exception.
