### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by sanatan99** [PredixDev/px-vis#114]
It is my understanding that the PX components are IE compatible. 

PX components use css variables, but this feature is not supported in IE. See here:
https://caniuse.com/#feat=css-variables

Therefore, it seems that PX components are not IE compatible. Is there a workaround for IE?

**Comment by mdwragg** [comment]
Polymer pollyfills this so it works in IE.

**Comment by mdwragg** [comment]
Follow the guide here: https://www.predix-ui.com/#/develop/theme
