### ISSUE TITLE
Uncaught ReferenceError: PxOverlayBehavior is not defined (blocker)

### ISSUE THREAD

**Issue by sanatan99** [PredixDev/px-vis#120]
Running into an issue which is blocking our build:

Uncaught ReferenceError: PxOverlayBehavior is not defined
    at Object.<anonymous> (px-overlay-container.html:11)
    at t (bootstrap 2da5f7efa735700c9b85:361)
    at Object.<anonymous> (px-overlay-behavior.html:4)
    at t (bootstrap 2da5f7efa735700c9b85:361)
    at Object.<anonymous> (px-overlay-content.html:4)
    at t (bootstrap 2da5f7efa735700c9b85:361)
    at Object.<anonymous> (px-dropdown.html:10)
    at t (bootstrap 2da5f7efa735700c9b85:361)
    at Object.<anonymous> (bundle.v1.0.0.js:29718)
    at t (bootstrap 2da5f7efa735700c9b85:361)

Looks like there is a circular reference in px-overlay-container.html which is referencing px-overlay-behavior.html which is again referencing px-overlay-container.html.

Here are our dependencies:
**"dependencies": {
    "polymer": "^1.9.0",
    "iron-ajax": "PolymerElements/iron-ajax#^1.4.0",
    "px-starter-kit-design": "https://github.com/PredixDev/px-starter-kit-design.git#^1.0.0",
    "px-dropdown": "^4.0.5",
    "px-modal": "^3.2.1",
    "px-alert-message": "^1.1.1",
    "intl-messageformat": "^1.1.0",
    "px-accordion": "^1.0.7",
    "iron-signals": "^1.0.3",
    "px-icon-set": "^2.0.17",
    "cytoscape": "^3.2.5",
    "px-tooltip": "^1.0.5",
    "px-toggle": "^2.1.0",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.24",
    "px-datetime-picker": "^2.0.2",
    "px-chip": "^1.1.0"
  },
  "resolutions": {
    "webcomponentsjs": "0.7.24",
    "test-fixture": "^3.0.0-rc.1",
    "px-datetime-common": "^3.0.0"
  },
  "devDependencies": {
    "test-fixture": "polymerelements/test-fixture#^1.1.0",
    "iron-test-helpers": "polymerelements/iron-test-helpers#~1.2.3",
    "web-component-tester": "4.3.1",
    "px-buttons-design": "^2.0.5",
    "px-tables-design": "^2.0.1",
    "px-forms-design": "^2.0.6",
    "px-headings-design": "^1.0.3",
    "px-list-ui-design": "^2.0.2",
    "px-button-group-design": "^2.0.5"
  }**

**Comment by nonmetalhail** [comment]
This does not appear to be at all related to px-vis. 

That reference was deleted in the latest version though. Update you bower

**Comment by sanatan99** [comment]
Build system does a fresh install each time, so bower components are getting updated. Issue still exists.

**Comment by nonmetalhail** [comment]
this is not the appropriate place for this. Locking this issue. Open in the correct repo if you expect help
