### ISSUE TITLE
px-vis-cursor/d3 attribute errors

### ISSUE THREAD

**Issue by kjrdel** [PredixDev/px-vis#123]
We are seeing Javascript errors stemming from px-vis-cursor when hovering over data on a time series plot where the coordinates are zero or undefined:

![cursor-errors](https://user-images.githubusercontent.com/28785823/37057674-2435bdbe-2156-11e8-9930-20ebe1673999.PNG)

We realize that this issue has been fixed in latest version 4 of px-vis:

[https://github.com/PredixDev/px-vis/commit/](https://github.com/PredixDev/px-vis/commit/c6df434cf6e1545f1c554369abe81f9bc27e7814)

However, our application was built using an older version of the Predix App Starter and we are therefore dependent upon an older version of px-theme and px-vis (currently using px-vis version 2.1.9).  

We were wondering if it might be possible to get this fix propagated down into version 2 until we are able to update our application to use the latest px-theme, designs, and visualization framework.  The errors are having an impact on our app's performance.

Thanks!

**Comment by nonmetalhail** [comment]
Sorry, we cannot support legacy versions.

You can turn off the cursor lines and circle to prevent the console errors, but with the tradeoff that  you wont have any indicator of where you are hovering over.
