### ISSUE TITLE
px-vis-zoom reset button doesnt display in the same location

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis#2]
The px-vis-zoom reset button which is shown when you do an on-chart zoom does not draw in the same location depending on if the top register is turned on and other factors.

**Comment by runn-vermel** [comment]
fixed!

**Comment by benoitjchevalier** [comment]
Has this been pushed? I still seem to be able to reproduce the issue by scrolling down the window before zooming

**Comment by benoitjchevalier** [comment]
Update: the issue I'm seeing is a different one. Scroll down the window, zoom => zoom button in wrong place. We should still fix it though ;)

**Comment by benoitjchevalier** [comment]
fixed
