### ISSUE TITLE
Tooltip: make sure the tooltip disappears when mouse leaves

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis#33]
Currently, sometimes the mouse can leave the svg and the tooltip will remain visible. Maybe due to a debouce? Investigate and ensure that the tooltip disappears.

**Comment by randyaskin** [comment]
Someone posted on the Forum a similar issue with px-chart, even though I wasn't seeing it in our demos. I wonder if they were confusing the HC version with the D3 version, or if the same issue occurs in both? 
http://forum.predix.io/questions/10503/tooltips-on-px-chart-always-stays-up.html

**Comment by nonmetalhail** [comment]
@randyaskin It is an issue in both I believe.
