### ISSUE TITLE
px-vis-pie _arcs property is not declared properly

### ISSUE THREAD

**Issue by predix-edgemanager-ui** [PredixDev/px-vis#40]
@benoitjchevalier 

_arcs property is missing the key word 'type' when declaring the property type.
Line 206 : https://github.com/PredixDev/px-vis/blob/master/px-vis-pie.html

Can you fix this asap please becasue this failed our code minification process.  Thanks alot!! 

@clementchi

**Comment by benoitjchevalier** [comment]
done, published as v0.1.17
