### ISSUE TITLE
reset zoom button broken 

### ISSUE THREAD

**Issue by nonmetalhail** [PredixDev/px-vis#53]
scroll and zoom, then it is in the wrong place

**Comment by nonmetalhail** [comment]
Not window scrollbar; container scrollbar

**Comment by benoitjchevalier** [comment]
this will go away as part of the toolbar rework

**Comment by nonmetalhail** [comment]
will be released in v1.0.0

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
