### ISSUE TITLE
Chart Navigator:  Data lines not rendering properly in nav chart if you adjust the timeline in range picker.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-vis#58]
If you have a range picker+timeseries+navigator chart and then you change the starting date in the range picker from say April to October, the data lines fall out of the navigator bar on the left hand side.
See screenshot.

Seeing this with vis version 0.6.14 and timeseries 0.4.4.

![nav_outofrange](https://cloud.githubusercontent.com/assets/10835611/19815410/949a61d4-9cf7-11e6-9d83-a8441ec61ae1.png)

**Comment by nonmetalhail** [comment]
Although true, this is only an issue if the range picker doesnt fetch new data. So it is mostly an edge case present in our demo. Marking as low priority bug

**Comment by benoitjchevalier** [comment]
fixed in v3
