### ISSUE TITLE
px-vis-scale recalculation of x axis domain

### ISSUE THREAD

**Issue by rupeshpadhye** [PredixDev/px-vis#59]
Hi,

Requirement -
  We have one Microservice providing time service data as per user chosen time frame.
on UI front, we are doing two way data binding for data consumption.
  We started analyzing from px-vis-spark and boiled down issue to px-vis-scale.
 [px-vis-spark raised issue](https://github.com/PredixDev/px-vis-spark/issues/1)
   is there a way to set new domain to `chartExtents` when time frame changes.

**Comment by nonmetalhail** [comment]
How are you setting the time frame? Is it with the range property from rangepicker? I do not know how spark is implemented, but the framework allows setting the range to control the extents

**Comment by rupeshpadhye** [comment]
@nonmetalhail  px-vis-spark internally uses  px-vis-line

- We pass start date and end date to time series(end point) and it gives data back in graph format. 
 So for our requirement `px-vis` should reset domain again (min and max time stamp) so that `px-vis-line` will be plotted from start ,currently it is remembering previous min and max.
 
- I think `SeriesConfig` is meant for one time config.
-I tried with '`px-vis-current-domain-x-updated`'  event  but no success .

@nonmetalhail  please throw some light on `domain-changed` variable shared across components and
how to notify px-vis-scale to recalculate him again via some event.

**Comment by nonmetalhail** [comment]
px-vis-current-domain-x-updated & domain-changed are notifications from scale. You should not fire them manually.

seriesConfig is the proper way to update the domain in your case. Be sure to use the Polymer API when making changes to the object.
