### ISSUE TITLE
Many polymer behavior annotations wrong?

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis#70]
I've tried to build a project with [polymer-build](https://github.com/Polymer/polymer-build).
It does fail b/c of some annotations issues like:

    /*
        @polymerBehavior PxVisBehavior.baseSize
    */
    PxVisBehavior.baseSize = {

    ...

    }

    /*
        @polymerBehavior PxVisBehavior.baseSize
    */
    PxVisBehavior.margins = {

    }

Is there a reason for that? Would you accept a PR that fixes these duplicates?

**Comment by nonmetalhail** [comment]
Hmm... the reason is a copy and paste error  ;) 

Yeah, we would love a PR if you find such errors. If not, please list which other behaviors you see that have such duplicate docs and we'll fix them.

Thanks
