### ISSUE TITLE
px-vis causes error on firefox if the element is hidden.

### ISSUE THREAD

**Issue by SiggansGE** [PredixDev/px-vis#73]
Hi,  Our team is using px-vis to develop a data analytic view app on Predix, and was getting error on Firefox.  Specifically, when using px-vis-axis,  drawTitle was throwing NS_ERROR_FAILURE.  We found out that this is a very specific bug that only exists on firefox, and can be found here https://bugzilla.mozilla.org/show_bug.cgi?id=612118, which had been open since 2010.   With SVG element, if getBBox is called while it is hidden, firefox will throw an error. 

The workaround I found that works is to catch the error on getBBox call, and use getBoundingClientRect() instead.

Steps to reproduce:  
Set px-vis under a hidden div and initialize it.

**Comment by nonmetalhail** [comment]
Thanks for the letting us know. We're put in fix in the next version

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
