### ISSUE TITLE
Events may get out of sync

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis#74]
## Expected behavior and actual behavior:

It appears that charts that use `<px-vis-event>` in a dom-repeat block may draw incorrect events on the canvas/svg. When the events-data array changes, `<px-vis-event>` tries to re-position existing event-lines and -data. From my testing it appears though that this does not work if events are removed from the array.

## Steps to reproduce the problem:

Remove any event-data element except the last one

## Code examples 

All _px-vis-*_ code-pen samples that I checked seem to be broken, so I created a simple example here:
https://github.build.ge.com/105042697/px-vis-74

**Comment by nonmetalhail** [comment]
Sorry about the codepens. They need to get updated for v1 and we haven't had a chance yet. Thanks for the sample.

**Comment by davidsteinberger** [comment]
Just FYI: commenting out _this._eventConfigChanged_ in px-vis-event.html should fix the issue at the expense that events are not _just_ repositioned on data change but removed and appended. 

    if(/*this._eventConfigChanged &&*/ this.eventGroup && this._doesD3HaveValues(this.eventGroup)) {

**Comment by nonmetalhail** [comment]
I'll separate the positioning and the drawing into separate methods/observers so it will remove when there is a change in the data/config but not when it just needs to be repositioned. Will be available in v1 release and when we push the next beta

**Comment by davidsteinberger** [comment]
Makes perfect sense. Thanks!

**Comment by davidsteinberger** [comment]
I've successfully tested this on latest master. Going to close the issue as the fix is already included in one of the beta releases.
