### ISSUE TITLE
px-vis-pie may not dead-center the title

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis#78]
## Expected behavior and actual behavior:

When using `<px-vis-pie donut="true">` I'd expect the chart to dead-center the title given that the user specifies `width` and `height` properly. From my testing that's not always the case. 

## Steps to reproduce the problem:

See code-pen sample mentioned on [predix-ui.com](https://www.predix-ui.com/#/components/px-vis-pie-chart/): http://codepen.io/pen/?&editors=1001
(_57 pints_ is too far to the left)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

All versions at least up to 1.0.0

**Comment by benoitjchevalier** [comment]
related to https://github.com/PredixDev/px-vis-pie-chart/issues/26
