### ISSUE TITLE
Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-vis#80]
I'm having issues w/ how v1.0.0-beta-3 defines the y-scale.

## Expected behavior and actual behavior:

Previously PxVisBehaviorScale.scale::_setMultiYScale() derived the range based on chart height and margins. Now it looks up the range from the axis:

    if(this.y) {
      for(var i = 0; i < this.axes.length; i++) {
        this.y[this.axes[i]].range([h, 0]);
      }
    }

While I really like the multi-y support, I'd be great if we could provide a fallback if `this.y[this.axes[i]].range` is not defined. If that's intended behavior please close the issue.

## Steps to reproduce the problem:

Use px-vis-timeseries in combination w/ v1.0.0-beta-3.
I replicated the issue [here](https://github.build.ge.com/105042697/px-vis-80).

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

v1.0.0-beta-3

## Screenshots (_optional, but very helpful_):

Uncaught TypeError: Cannot read property 'range' of undefined
    at HTMLElement._setMultiYScale (px-vis-behavior-scale.html:110)

**Comment by nonmetalhail** [comment]
I believe I have fixed this and pushed to master; we will release the fix with the v1.0.0 release later this week. If you want to confirm that it works, please try it on master. If you need a temporary fallback, I believe v1.0.0-beta tag does not have this issue.

**Comment by davidsteinberger** [comment]
I'm hesitant going back to beta as it's fairly old by now, but I just tried master and it's fixed there. Thanks!

**Comment by nonmetalhail** [comment]
Thanks for confirming. We're officially releasing v1 later this week so this fix will be released soon.

**Comment by benoitjchevalier** [comment]
Fixed with 1.0.0 release
