### ISSUE TITLE
[Perf] line-canvas-progressive-rendering

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-vis#81]
We can improve progressive rendering. Currently it slices the data in X batches and render each in a requestAnimationFrame. However there's no guarantee of how much/little data we can render in 1 animation frame, so we might end up:
- taking too long (relatively unlikely at the moment given the batches sizes)
- spending time doing nothing. Likely at the moment, especially if some of your data has been filtered out (you can spend the whole frame doing nothing)

We could/should
- keep a filtered version of the dataset (would also help for tooltip/registers and potentially other things)
- 'reverse' the progressive rendering logic so that we render per slice of time instead of slice of data

**Comment by benoitjchevalier** [comment]
We now expose the number of points that will be processed per frame, but this is not  good enough since:
 - timespan per frame might vary depending on display refresh rate, iframe, slow frames, etc
 - processing power isn't  constant (depends on browser, cpu...)

Since requestAnimationFrame gives us a timestamp (1ms resolution) we should use it to measure time elapsed between 2 animation frames and dynamically adjust the number of points processed all along the progressive rendering (on the first (and subsequent) frame measure our average processing power: X points per ms)

**Comment by benoitjchevalier** [comment]
Currently rewriting a centralized renderer dynamically adjusting the number of points to render per frame based on rendering type.

**Comment by nonmetalhail** [comment]
released with v3
