### ISSUE TITLE
Importing files that do not exist

### ISSUE THREAD

**Issue by sjw787** [PredixDev/px-vis#85]
Hello, 
While running vulcanize on my project I ran into a few errors due to what looks like old import statements where the file name has changed from previous versions.

Vulcanize likes to fail when it cannot find a file in your project and points out the culprit file. 

The first two errors I stumbled upon was in px-vis/px-vis-xy-chart.html on lines 13 and 18

`<link rel="import" href="../px-vis/px-vis-line.html"/>
`
and
`<link rel="import" href="../px-vis/px-vis-zoom.html"/>
`

The last one I found was in px-vis/px-vis-spark.html on line 8 for importing 
`<link rel="import" href="../px-vis/px-vis-line.html"/>` once more.

I am trying to use the new px-vis-timeseries in my project and these are keeping me from vulcanizing it. 

Thanks!

**Comment by benoitjchevalier** [comment]
Hello,

as part of the v1.0.0 release of px-vis `px-vis-line` and `px-vis-zoom` have been deleted. It seems like you're loading vis 1.0.0 but an old version of xy chart. Make sure all your charts versions are up to date (v1.0.0)

**Comment by sjw787** [comment]
Ohh okay I see now. Thank you very much!
