### ISSUE TITLE
Moving PredixDev packages to npm registry?

### ISSUE THREAD

**Issue by 6palace** [PredixDev/px-vis#92]
Since Bower officially deprecated a few days ago, I have been looking at moving PredixDev package installation to npm. However, the npm registry does not have any PredixDev packages registered yet.
Is there any chance you will be registering to other package registries in the future? I would hate to have to substitute all dependencies with git addresses.

**Comment by mdwragg** [comment]
Bower still lives! As recently as Friday, the recommendation was to continue to use bower distributing web components:

https://youtu.be/Ucq9F-7Xp8I?t=1876

That said, as soon as the yarn + flat twiddle is bedded in and working (not just for us but for our 3rd party dependencies also) we will start to evaluate that.

Thanks for your question.

CC @PredixDev/px
