### ISSUE TITLE
"px-vis-axis-drag.html" is referenced but does not exist in the repository

### ISSUE THREAD

**Issue by Abdelkrim** [PredixDev/px-vis#93]
# Submit an Issue

* "px-vis/px-vis-html" references "px-vis-axis-drag.html" (`<link rel="import" href="px-vis-axis-drag.html">`)

## Expected behavior and actual behavior:

* the file px-vis/px-vis-axis-drag.html should exist inside the px-vis directory

## Steps to reproduce the problem:

* Look into the following directory: https://github.com/PredixDev/px-vis

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

* NOT RELEVANT

## Screenshots (_optional, but very helpful_):

* NOT RELEVANT

**Comment by nonmetalhail** [comment]
Your running into some legacy code that should be cleaned up. Px-vis-axis-drag is now a behavior file. Px-vis-axis-drag.html itself should probably be deleted as it is no longer used and not maintained. It's best to look here for which components are currently offered and their API: https://www.predix-ui.com/#/components/px-vis/
